# Generated by Django 5.1.1 on 2024-09-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('payment_gateway', models.CharField(max_length=50)),
                ('status', models.CharField(default='In Progress', max_length=25)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
