# Generated by Django 5.1.1 on 2024-10-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentToken',
        ),
    ]
