# Generated by Django 5.1.1 on 2024-10-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='token',
        ),
    ]
